#! /usr/bin/env python
# encoding: utf-8

VERSION='1.1.0'
APPNAME='phantomjs'

top = '..'
out = 'build'

def options(opt):
	opt.load('compiler_cxx compiler_c qt4')

def configure(conf):
	conf.load('compiler_cxx compiler_c qt4')
	conf.env.append_value('CXXFLAGS', ['-g']) # test

def build(bld):
	bld.recurse('gif')
	bld.program(
		features = 'qt4 cxx cxxprogram',
		uselib   = 'QTCORE QTWEBKIT',
        use      = 'gif',
		source   = ['main.cpp', 'phantomjs.qrc', 'csconverter.cpp', 'networkaccessmanager.cpp',
                    'phantom.cpp', 'utils.cpp', 'webpage.cpp', 'gif/gifwriter.cpp'],
		target   = 'window',
		includes = '. ./gif',
	)

